// Code generated by scripts/render-logo-face.py. DO NOT EDIT.

package tui

// wordmarkRows is `another` rasterized from JetBrains Mono ExtraBold at
// 10 square sub-pixels and folded into half-block characters, so the
// mark occupies 5 terminal rows instead of the 10 a whole-block face
// would need. Each row is exactly markWidth cells wide.
var wordmarkRows = []string{
	"                          ██     ██                     ",
	" ▄▄██▄  ▄█▄▄█▄   ▄▄██▄▄ ▄▄███▄█  ██▄██▄   ▄██▄▄  ▄█▄▄█▄ ",
	" ▀▄▄▄██ ██▀ ▀██  ██  ██   ██     ██  ██  ██▄▄██▄ ██▀ ▀██",
	"██▀▀▀██ ██   ██  ██  ██   ██     ██  ██  ██▀▀    ██     ",
	"▀███▀██ ▀█   ██  ▀████▀    ████  ██  ▀█  ▀████▀  ▀█     ",
}

const markWidth = 56
