#!/usr/bin/env python3
"""Generate the TUI goodbye wordmark from a real typeface.

A terminal cell is about 1:2, so letterforms drawn from whole blocks are twice
as tall per pixel as they are wide and the mark towers over everything else on
screen. Packing two sub-rows into one cell with the half-block characters
▀ ▄ █ makes the sub-pixel grid square, which is the grid a typeface is actually
designed on. The wordmark is therefore rasterized from JetBrains Mono
ExtraBold rather than hand-drawn.

The output is a rendered raster of seven letters, the same way a logo image is
output from a font; the typeface itself is neither embedded nor redistributed.

Requires Pillow and JetBrains Mono ExtraBold. Regenerate with:

    python3 scripts/render-logo-face.py > internal/tui/logo_face.go
"""

from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

WORD = "another"
SUB_ROWS = 10  # 10 square sub-pixels tall -> 5 terminal cell rows
THRESHOLD = 128

FACE_CANDIDATES = [
    Path.home() / "Library/Fonts/JetBrainsMono-ExtraBold.ttf",
    Path("/opt/homebrew/Caskroom/font-jetbrains-mono/2.304/fonts/ttf/JetBrainsMono-ExtraBold.ttf"),
    Path("/usr/share/fonts/truetype/jetbrains-mono/JetBrainsMono-ExtraBold.ttf"),
]


def find_face() -> Path:
    for path in FACE_CANDIDATES:
        if path.exists():
            return path
    sys.exit("JetBrains Mono ExtraBold not found; install font-jetbrains-mono")


def rasterize(face: Path) -> list[list[bool]]:
    """Set the word, crop to its ink, and scale to SUB_ROWS square sub-pixels."""
    size = SUB_ROWS
    while size < SUB_ROWS * 8:
        font = ImageFont.truetype(str(face), size)
        box = font.getbbox(WORD)
        if box[3] - box[1] >= SUB_ROWS * 4:
            break
        size += 2
    canvas = Image.new("L", (size * len(WORD) * 2, size * 3), 0)
    ImageDraw.Draw(canvas).text((size, size), WORD, font=font, fill=255)
    ink = canvas.crop(canvas.getbbox())
    width = max(1, round(ink.width * SUB_ROWS / ink.height))
    small = ink.resize((width, SUB_ROWS), Image.Resampling.LANCZOS)
    return [[small.getpixel((x, y)) >= THRESHOLD for x in range(width)]
            for y in range(SUB_ROWS)]


def pack(grid: list[list[bool]]) -> list[str]:
    """Fold each pair of sub-rows into one row of half-block characters."""
    rows = []
    for y in range(0, len(grid), 2):
        top = grid[y]
        bottom = grid[y + 1] if y + 1 < len(grid) else [False] * len(top)
        rows.append("".join(
            "█" if t and b else "▀" if t else "▄" if b else " "
            for t, b in zip(top, bottom)
        ))
    return rows


def main() -> None:
    rows = pack(rasterize(find_face()))
    width = len(rows[0])
    print("// Code generated by scripts/render-logo-face.py. DO NOT EDIT.")
    print()
    print("package tui")
    print()
    print("// wordmarkRows is `another` rasterized from JetBrains Mono ExtraBold at")
    print(f"// {SUB_ROWS} square sub-pixels and folded into half-block characters, so the")
    print(f"// mark occupies {len(rows)} terminal rows instead of the {SUB_ROWS} a whole-block face")
    print("// would need. Each row is exactly markWidth cells wide.")
    print("var wordmarkRows = []string{")
    for row in rows:
        print(f'\t"{row}",')
    print("}")
    print()
    print(f"const markWidth = {width}")


if __name__ == "__main__":
    main()
